In [1]:
print("Nitin")

Nitin

In [11]:
import requests
import json

apikey = "9a15598c-faeb-41f8-879c-9a60959a6371"
id="1f16f05e-e25c-43a1-ba00-331b1d2c3b8a"
response = requests.get("https://api.cricapi.com/v1/match_info?apikey="+apikey+"&offset=0&id="+id)
def myobj(obj):
    text = json.dumps(obj, sort_keys=True, indent=4)
    data = json.loads(text)['data']
    return data
    teams = json.loads(text)['data']['teams']
    print("----------------------------Match Info -----------------")
    print(" Name - "+data['name']+" \n "+"Match Type -   "+data['matchType']+" \n ")    
    print(" status - "+data['status'] +" venue - "+ str(data['venue']) +" date - "+ str(data['date']) )    
    for tm in teams:
     print(" tm - "+tm )    

df = myobj(response.json())

In [23]:
import requests
import json

apikey = "9a15598c-faeb-41f8-879c-9a60959a6371"
response = requests.get("https://api.cricapi.com/v1/matches?apikey="+apikey+"&offset=1000")
def myobj(obj):
    text = json.dumps(obj, sort_keys=True, indent=4)
    data = json.loads(text)['data']
    return data
    # print(data)
    print("----------------------------Match List -----------------")
    for value in data:
        print(" Name - "+value['name']+"\n"+" status - "+value['status']+"\n"+" venue -  "+value['venue']+"\n"+"dateTimeGMT - "+value['dateTimeGMT']+"\n")    

df = myobj(response.json())
len(df)

25

In [19]:
df

[{'bbbEnabled': False,
  'date': '2023-02-28',
  'dateTimeGMT': '2023-02-28T05:30:00',
  'fantasyEnabled': False,
  'hasSquad': True,
  'id': 'd86ba08f-56bf-40d0-87cd-2f84b648a1e6',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 'odi',
  'name': 'United Arab Emirates vs Papua New Guinea, 2nd Match',
  'series_id': '638e7c98-fe04-4c84-946e-699f0abdc00c',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/68-637877083835752068.webp',
    'name': 'Papua New Guinea',
    'shortname': 'PNG'},
   {'img': 'https://g.cricapi.com/img/teams/92-637877081068315608.webp',
    'name': 'United Arab Emirates',
    'shortname': 'UAE'}],
  'teams': ['United Arab Emirates', 'Papua New Guinea'],
  'venue': 'Dubai International Cricket Stadium, Dubai'},
 {'bbbEnabled': False,
  'date': '2023-02-27',
  'dateTimeGMT': '2023-02-27T05:30:00',
  'fantasyEnabled': False,
  'hasSquad': True,
  'id': '2ee99136-ffaa-40c7-b283-283fa465968d',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 'odi',
  'name': 'Papua New Guinea vs Nepal, 1st Match',
  'series_id': '638e7c98-fe04-4c84-946e-699f0abdc00c',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/54-637877084789981539.webp',
    'name': 'Nepal',
    'shortname': 'NEP'},
   {'img': 'https://g.cricapi.com/img/teams/68-637877083835752068.webp',
    'name': 'Papua New Guinea',
    'shortname': 'PNG'}],
  'teams': ['Papua New Guinea', 'Nepal'],
  'venue': 'Dubai International Cricket Stadium, Dubai'},
 {'bbbEnabled': False,
  'date': '2023-03-04',
  'dateTimeGMT': '2023-03-04T17:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': 'e056f0fd-9cbd-48a8-bd3a-da3c66a44149',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Argentina vs Cayman Islands, 15th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/579-637869397212602812.webp',
    'name': 'Argentina',
    'shortname': 'ARG'},
   {'img': 'https://g.cricapi.com/img/teams/593-637874526018520738.webp',
    'name': 'Cayman Islands',
    'shortname': 'CAYM'}],
  'teams': ['Argentina', 'Cayman Islands'],
  'venue': 'Belgrano Athletic Club Ground, Belgrano, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-03-04',
  'dateTimeGMT': '2023-03-04T13:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': '7245653c-8eeb-480b-9924-2ac92297e163',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Panama vs Belize, 14th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/586-637871097716183997.webp',
    'name': 'Belize',
    'shortname': 'BLZ'},
   {'img': 'https://g.cricapi.com/img/teams/639-637870990595820825.webp',
    'name': 'Panama',
    'shortname': 'PNM'}],
  'teams': ['Panama', 'Belize'],
  'venue': 'Belgrano Athletic Club Ground, Belgrano, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-03-04',
  'dateTimeGMT': '2023-03-04T13:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': '1fe6b1d4-ebdd-401f-ba0e-15215dce8121',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Bahamas vs Bermuda, 13th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/582-637872826836006664.webp',
    'name': 'Bahamas',
    'shortname': 'BHM'},
   {'img': 'https://g.cricapi.com/img/teams/587-637865062552981767.webp',
    'name': 'Bermuda',
    'shortname': 'BMUDA'}],
  'teams': ['Bahamas', 'Bermuda'],
  'venue': 'Hurlingham Club Ground, Hurlingham, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-03-02',
  'dateTimeGMT': '2023-03-02T17:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': '1c3b1797-91e0-40e2-9e7b-0e1ccb4ab50d',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Cayman Islands vs Panama, 12th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/593-637874526018520738.webp',
    'name': 'Cayman Islands',
    'shortname': 'CAYM'},
   {'img': 'https://g.cricapi.com/img/teams/639-637870990595820825.webp',
    'name': 'Panama',
    'shortname': 'PNM'}],
  'teams': ['Cayman Islands', 'Panama'],
  'venue': 'St Albans Club, Corimayo, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-03-02',
  'dateTimeGMT': '2023-03-02T13:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': '5e28ab08-8b87-42e3-9b84-c6316a50f7b5',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Argentina vs Bahamas, 11th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/579-637869397212602812.webp',
    'name': 'Argentina',
    'shortname': 'ARG'},
   {'img': 'https://g.cricapi.com/img/teams/582-637872826836006664.webp',
    'name': 'Bahamas',
    'shortname': 'BHM'}],
  'teams': ['Argentina', 'Bahamas'],
  'venue': 'St Albans Club, Corimayo, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-03-02',
  'dateTimeGMT': '2023-03-02T13:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': 'e13217c0-58df-491c-8d9e-68a7e783b0d0',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Bermuda vs Belize, 10th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/586-637871097716183997.webp',
    'name': 'Belize',
    'shortname': 'BLZ'},
   {'img': 'https://g.cricapi.com/img/teams/587-637865062552981767.webp',
    'name': 'Bermuda',
    'shortname': 'BMUDA'}],
  'teams': ['Bermuda', 'Belize'],
  'venue': 'Hurlingham Club Ground, Hurlingham, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-02-28',
  'dateTimeGMT': '2023-02-28T17:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': '13fd1be3-9b4a-403b-9d5c-79ebe5dfd3b0',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Argentina vs Belize, 9th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/579-637869397212602812.webp',
    'name': 'Argentina',
    'shortname': 'ARG'},
   {'img': 'https://g.cricapi.com/img/teams/586-637871097716183997.webp',
    'name': 'Belize',
    'shortname': 'BLZ'}],
  'teams': ['Argentina', 'Belize'],
  'venue': 'St Albans Club, Corimayo, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-02-28',
  'dateTimeGMT': '2023-02-28T13:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': '9a97d039-3dca-4bf6-b017-fc3351712d5b',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Cayman Islands vs Bahamas, 7th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/582-637872826836006664.webp',
    'name': 'Bahamas',
    'shortname': 'BHM'},
   {'img': 'https://g.cricapi.com/img/teams/593-637874526018520738.webp',
    'name': 'Cayman Islands',
    'shortname': 'CAYM'}],
  'teams': ['Cayman Islands', 'Bahamas'],
  'venue': 'Belgrano Athletic Club Ground, Belgrano, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-02-28',
  'dateTimeGMT': '2023-02-28T13:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': '23d1c45d-08e5-4c42-9ca0-82e1e21358f4',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Bermuda vs Panama, 8th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/587-637865062552981767.webp',
    'name': 'Bermuda',
    'shortname': 'BMUDA'},
   {'img': 'https://g.cricapi.com/img/teams/639-637870990595820825.webp',
    'name': 'Panama',
    'shortname': 'PNM'}],
  'teams': ['Bermuda', 'Panama'],
  'venue': 'St Albans Club, Corimayo, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-02-26',
  'dateTimeGMT': '2023-02-26T17:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': '968794e5-3863-4ba6-acdf-7ad8aabbfdea',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Argentina vs Bermuda, 6th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/579-637869397212602812.webp',
    'name': 'Argentina',
    'shortname': 'ARG'},
   {'img': 'https://g.cricapi.com/img/teams/587-637865062552981767.webp',
    'name': 'Bermuda',
    'shortname': 'BMUDA'}],
  'teams': ['Argentina', 'Bermuda'],
  'venue': 'Belgrano Athletic Club Ground, Belgrano, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-02-26',
  'dateTimeGMT': '2023-02-26T13:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': 'c43735bd-860b-42b9-8c49-e4f9243a7bbf',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Cayman Islands vs Belize, 4th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/586-637871097716183997.webp',
    'name': 'Belize',
    'shortname': 'BLZ'},
   {'img': 'https://g.cricapi.com/img/teams/593-637874526018520738.webp',
    'name': 'Cayman Islands',
    'shortname': 'CAYM'}],
  'teams': ['Cayman Islands', 'Belize'],
  'venue': 'Hurlingham Club Ground, Hurlingham, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-02-26',
  'dateTimeGMT': '2023-02-26T13:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': '9f54bd17-c270-4c4f-a124-26ea086e92f0',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Bahamas vs Panama, 5th Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/582-637872826836006664.webp',
    'name': 'Bahamas',
    'shortname': 'BHM'},
   {'img': 'https://g.cricapi.com/img/teams/639-637870990595820825.webp',
    'name': 'Panama',
    'shortname': 'PNM'}],
  'teams': ['Bahamas', 'Panama'],
  'venue': 'Belgrano Athletic Club Ground, Belgrano, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-02-26',
  'dateTimeGMT': '2023-02-26T08:00:00',
  'fantasyEnabled': False,
  'hasSquad': True,
  'id': 'fb8a83ba-0b25-40e9-a7cc-cbf454bfa774',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 'test',
  'name': 'Warriors vs Knights, Division 1',
  'series_id': '5d591476-b27d-45f5-8f18-a73ab326664d',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/40-637992688759741358.webp',
    'name': 'Knights',
    'shortname': 'KNG'},
   {'img': 'https://g.cricapi.com/img/teams/98-637987556857963180.webp',
    'name': 'Warriors',
    'shortname': 'WAR'}],
  'teams': ['Warriors', 'Knights'],
  'venue': "St George's Park, Gqeberha"},
 {'bbbEnabled': False,
  'date': '2023-02-26',
  'dateTimeGMT': '2023-02-26T08:00:00',
  'fantasyEnabled': False,
  'hasSquad': True,
  'id': '5fe9acae-4fed-4fb7-a19d-090b8d571c31',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 'test',
  'name': 'Lions vs Western Province, Division 1',
  'series_id': '5d591476-b27d-45f5-8f18-a73ab326664d',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/43-638016114998237773.webp',
    'name': 'Lions',
    'shortname': 'LIONS'},
   {'img': 'https://g.cricapi.com/img/teams/104-637987555401464222.webp',
    'name': 'Western Province',
    'shortname': 'WPR'}],
  'teams': ['Lions', 'Western Province'],
  'venue': 'The Wanderers Stadium, Johannesburg'},
 {'bbbEnabled': False,
  'date': '2023-02-26',
  'dateTimeGMT': '2023-02-26T08:00:00',
  'fantasyEnabled': False,
  'hasSquad': True,
  'id': 'f6302eaf-733f-4df4-a787-e2cd431c3503',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 'test',
  'name': 'Dolphins vs Titans, Division 1',
  'series_id': '5d591476-b27d-45f5-8f18-a73ab326664d',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/20-637993514627926036.webp',
    'name': 'Dolphins',
    'shortname': 'DOL'},
   {'img': 'https://g.cricapi.com/img/teams/89-637987557693726758.webp',
    'name': 'Titans',
    'shortname': 'TITNS'}],
  'teams': ['Dolphins', 'Titans'],
  'venue': 'Kingsmead, Durban'},
 {'bbbEnabled': False,
  'date': '2023-02-26',
  'dateTimeGMT': '2023-02-26T13:00:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': 'de945317-7f23-4e24-bb81-d30a25d62024',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Tbc vs Tbc, Final',
  'series_id': 'f2f02a29-5800-4b95-8774-b170cdbfd308',
  'status': 'Match not started',
  'teams': ['Tbc', 'Tbc'],
  'venue': 'Newlands, Cape Town'},
 {'bbbEnabled': False,
  'date': '2023-02-25',
  'dateTimeGMT': '2023-02-25T17:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': 'cd324b65-af4d-47ef-82c1-9948d9d75327',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Belize vs Bahamas, 3rd Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/582-637872826836006664.webp',
    'name': 'Bahamas',
    'shortname': 'BHM'},
   {'img': 'https://g.cricapi.com/img/teams/586-637871097716183997.webp',
    'name': 'Belize',
    'shortname': 'BLZ'}],
  'teams': ['Belize', 'Bahamas'],
  'venue': 'St Albans Club, Corimayo, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-02-25',
  'dateTimeGMT': '2023-02-25T17:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': 'bbe33e9f-c1e5-48be-83ee-755f8ca1767c',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Bermuda vs Cayman Islands, 2nd Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/587-637865062552981767.webp',
    'name': 'Bermuda',
    'shortname': 'BMUDA'},
   {'img': 'https://g.cricapi.com/img/teams/593-637874526018520738.webp',
    'name': 'Cayman Islands',
    'shortname': 'CAYM'}],
  'teams': ['Bermuda', 'Cayman Islands'],
  'venue': 'Hurlingham Club Ground, Hurlingham, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-02-25',
  'dateTimeGMT': '2023-02-25T13:30:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': '262bddd4-0844-47d6-bec2-abce9d9b75de',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Argentina vs Panama, 1st Match',
  'series_id': '0991ac08-8633-427f-8eb4-d1adc035e8b5',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/579-637869397212602812.webp',
    'name': 'Argentina',
    'shortname': 'ARG'},
   {'img': 'https://g.cricapi.com/img/teams/639-637870990595820825.webp',
    'name': 'Panama',
    'shortname': 'PNM'}],
  'teams': ['Argentina', 'Panama'],
  'venue': 'Hurlingham Club Ground, Hurlingham, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-02-25',
  'dateTimeGMT': '2023-02-25T05:30:00',
  'fantasyEnabled': False,
  'hasSquad': True,
  'id': 'b5584657-6e66-4bc4-81d1-36c1af3268d5',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 'odi',
  'name': 'United Arab Emirates vs Namibia, 2nd Match (Rescheduled)',
  'series_id': '638e7c98-fe04-4c84-946e-699f0abdc00c',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/53-637877082656229722.webp',
    'name': 'Namibia',
    'shortname': 'NAM'},
   {'img': 'https://g.cricapi.com/img/teams/92-637877081068315608.webp',
    'name': 'United Arab Emirates',
    'shortname': 'UAE'}],
  'teams': ['United Arab Emirates', 'Namibia'],
  'venue': 'Dubai International Cricket Stadium, Dubai'},
 {'bbbEnabled': False,
  'date': '2023-02-22',
  'dateTimeGMT': '2023-02-22T18:00:00',
  'fantasyEnabled': True,
  'hasSquad': True,
  'id': '07adc7f6-cb40-4b30-8721-37e7f2fd43dd',
  'matchEnded': True,
  'matchStarted': True,
  'matchType': 't20',
  'name': 'Argentina vs Bermuda, 2nd T20I',
  'score': [{'inning': 'Bermuda Inning 1', 'o': 20, 'r': 226, 'w': 4},
   {'inning': 'Argentina Inning 1', 'o': 20, 'r': 119, 'w': 5}],
  'series_id': 'cebaa797-c95e-4269-b293-c5f15f048fca',
  'status': 'Bermuda won by 107 runs',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/579-637869397212602812.webp',
    'name': 'Argentina',
    'shortname': 'ARG'},
   {'img': 'https://g.cricapi.com/img/teams/587-637865062552981767.webp',
    'name': 'Bermuda',
    'shortname': 'BMUDA'}],
  'teams': ['Argentina', 'Bermuda'],
  'venue': 'Belgrano Athletic Club Ground, Belgrano, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-02-21',
  'dateTimeGMT': '2023-02-21T17:00:00',
  'fantasyEnabled': True,
  'hasSquad': True,
  'id': '99a12bb7-3106-4d93-a9a3-05bf9543e729',
  'matchEnded': True,
  'matchStarted': True,
  'matchType': 't20',
  'name': 'Argentina vs Bermuda, 1st T20I',
  'score': [{'inning': 'Argentina Inning 1', 'o': 17.2, 'r': 77, 'w': 10},
   {'inning': 'Bermuda Inning 1', 'o': 15.5, 'r': 78, 'w': 4}],
  'series_id': 'cebaa797-c95e-4269-b293-c5f15f048fca',
  'status': 'Bermuda won by 6 wkts',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/579-637869397212602812.webp',
    'name': 'Argentina',
    'shortname': 'ARG'},
   {'img': 'https://g.cricapi.com/img/teams/587-637865062552981767.webp',
    'name': 'Bermuda',
    'shortname': 'BMUDA'}],
  'teams': ['Argentina', 'Bermuda'],
  'venue': 'St Albans Club, Corimayo, Buenos Aires'},
 {'bbbEnabled': False,
  'date': '2023-05-21',
  'dateTimeGMT': '2023-05-21T14:00:00',
  'fantasyEnabled': False,
  'hasSquad': False,
  'id': '9759d12a-14a6-42c2-bbe2-833c6f612ceb',
  'matchEnded': False,
  'matchStarted': False,
  'matchType': 't20',
  'name': 'Royal Challengers Bangalore vs Gujarat Titans, 70th Match',
  'series_id': 'c75f8952-74d4-416f-b7b4-7da4b4e3ae6e',
  'status': 'Match not started',
  'teamInfo': [{'img': 'https://g.cricapi.com/img/teams/172-637852957798476823.png',
    'name': 'Gujarat Titans',
    'shortname': 'GT'},
   {'img': 'https://g.cricapi.com/img/teams/261-637852957972423711.png',
    'name': 'Royal Challengers Bangalore',
    'shortname': 'RCB'}],
  'teams': ['Royal Challengers Bangalore', 'Gujarat Titans'],
  'venue': 'M.Chinnaswamy Stadium, Bengaluru'}]

In [30]:
import pandas as pd
df = pd.read_csv("/Users/nyzy/Downloads/all_male_csv2/64012.csv")
pd.set_option('display.max_columns', None)
df

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,64012,2002/03,2002-12-26,Melbourne Cricket Ground,1,0.1,Australia,England,JL Langer,ML Hayden,AR Caddick,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,64012,2002/03,2002-12-26,Melbourne Cricket Ground,1,0.2,Australia,England,JL Langer,ML Hayden,AR Caddick,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,64012,2002/03,2002-12-26,Melbourne Cricket Ground,1,0.3,Australia,England,ML Hayden,JL Langer,AR Caddick,4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,64012,2002/03,2002-12-26,Melbourne Cricket Ground,1,0.4,Australia,England,ML Hayden,JL Langer,AR Caddick,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,64012,2002/03,2002-12-26,Melbourne Cricket Ground,1,0.5,Australia,England,ML Hayden,JL Langer,AR Caddick,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2310,64012,2002/03,2002-12-26,Melbourne Cricket Ground,4,22.3,Australia,England,AC Gilchrist,ML Love,AR Caddick,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2311,64012,2002/03,2002-12-26,Melbourne Cricket Ground,4,22.4,Australia,England,ML Love,AC Gilchrist,AR Caddick,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2312,64012,2002/03,2002-12-26,Melbourne Cricket Ground,4,22.5,Australia,England,ML Love,AC Gilchrist,AR Caddick,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2313,64012,2002/03,2002-12-26,Melbourne Cricket Ground,4,22.6,Australia,England,ML Love,AC Gilchrist,AR Caddick,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2314,64012,2002/03,2002-12-26,Melbourne Cricket Ground,4,23.1,Australia,England,AC Gilchrist,ML Love,SJ Harmison,4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
import csv

easy_csv = []

with open('/Users/nyzy/Downloads/all_male_csv2 2/64012_info.csv', 'r') as csvfile:
   test = csv.reader(csvfile, delimiter=',')
   for row in test:
      print(row)

['version', '2.2.0']
['info', 'balls_per_over', '6']
['info', 'team', 'Australia']
['info', 'team', 'England']
['info', 'gender', 'male']
['info', 'season', '2002/03']
['info', 'date', '2002/12/26']
['info', 'date', '2002/12/27']
['info', 'date', '2002/12/28']
['info', 'date', '2002/12/29']
['info', 'date', '2002/12/30']
['info', 'event', 'England tour of Australia']
['info', 'match_number', '4']
['info', 'venue', 'Melbourne Cricket Ground']
['info', 'city', 'Melbourne']
['info', 'toss_winner', 'Australia']
['info', 'toss_decision', 'bat']
['info', 'player_of_match', 'JL Langer']
['info', 'umpire', 'DL Orchard']
['info', 'umpire', 'RB Tiffin']
['info', 'tv_umpire', 'DB Hair']
['info', 'match_referee', 'Wasim Raja']
['info', 'winner', 'Australia']
['info', 'winner_wickets', '5']
['info', 'player', 'Australia', 'JL Langer']
['info', 'player', 'Australia', 'ML Hayden']
['info', 'player', 'Australia', 'RT Ponting']
['info', 'player', 'Australia', 'DR Martyn']
['info', 'player', 'Australia', 'SR Waugh']
['info', 'player', 'Australia', 'ML Love']
['info', 'player', 'Australia', 'AC Gilchrist']
['info', 'player', 'Australia', 'B Lee']
['info', 'player', 'Australia', 'JN Gillespie']
['info', 'player', 'Australia', 'SCG MacGill']
['info', 'player', 'Australia', 'GD McGrath']
['info', 'player', 'England', 'ME Trescothick']
['info', 'player', 'England', 'MP Vaughan']
['info', 'player', 'England', 'MA Butcher']
['info', 'player', 'England', 'N Hussain']
['info', 'player', 'England', 'RKJ Dawson']
['info', 'player', 'England', 'RWT Key']
['info', 'player', 'England', 'JP Crawley']
['info', 'player', 'England', 'C White']
['info', 'player', 'England', 'JS Foster']
['info', 'player', 'England', 'AR Caddick']
['info', 'player', 'England', 'SJ Harmison']
['info', 'registry', 'people', 'AC Gilchrist', '2b6e6dec']
['info', 'registry', 'people', 'AJ Tudor', '1d622276']
['info', 'registry', 'people', 'AR Caddick', '25020f9d']
['info', 'registry', 'people', 'B Lee', 'dd09ff8e']
['info', 'registry', 'people', 'C White', 'f44af07f']
['info', 'registry', 'people', 'DB Hair', '492e1a8e']
['info', 'registry', 'people', 'DL Orchard', 'a7df1d20']
['info', 'registry', 'people', 'DR Martyn', '69762509']
['info', 'registry', 'people', 'GD McGrath', 'ee7d0c82']
['info', 'registry', 'people', 'JL Langer', '94198ef4']
['info', 'registry', 'people', 'JN Gillespie', '74234d66']
['info', 'registry', 'people', 'JP Crawley', 'c16b33fa']
['info', 'registry', 'people', 'JS Foster', 'e68dd455']
['info', 'registry', 'people', 'MA Butcher', '8fb88ee3']
['info', 'registry', 'people', 'ME Trescothick', 'ea42ddb9']
['info', 'registry', 'people', 'ML Hayden', 'd8699ab7']
['info', 'registry', 'people', 'ML Love', 'c4b94434']
['info', 'registry', 'people', 'MP Vaughan', '6e1b1ec0']
['info', 'registry', 'people', 'N Hussain', 'f76ffa81']
['info', 'registry', 'people', 'RB Tiffin', '89087a0d']
['info', 'registry', 'people', 'RKJ Dawson', 'd1d0b5ed']
['info', 'registry', 'people', 'RT Ponting', '7d415ea5']
['info', 'registry', 'people', 'RWT Key', 'bcb01d8c']
['info', 'registry', 'people', 'SCG MacGill', '60dac349']
['info', 'registry', 'people', 'SJ Harmison', 'c16d2e28']
['info', 'registry', 'people', 'SR Waugh', '622dee94']
['info', 'registry', 'people', 'Wasim Raja', 'd8bce357']

In [1]:
  
import json
  
# Opening JSON file
f = open('/Users/nyzy/data/recently_played_30_male_json/1239534.json')
  
# returns JSON object as 
# a dictionary
data = json.load(f)

In [2]:
data.keys()

dict_keys(['meta', 'info', 'innings'])

In [6]:
data["info"]["teams"]

['Sri Lanka', 'England']

In [7]:
dictionary = {
  **dict.fromkeys(['a', 'b'], 1),
  **dict.fromkeys(['c', 'd'], 2),
  }

assert dictionary['a'] == 1
assert dictionary['b'] == 1

In [8]:
dictionary

{'a': 1, 'b': 1, 'c': 2, 'd': 2}

In [11]:
my_dict = dict.fromkeys(['a', 'c', 'd'], 10)
my_dict.update(dict.fromkeys(['c', 'e'], 20))

In [50]:
import pandas as pd 
from data_access_layer.flexible_data_read import FlexDataRead
import os 
import constants
list_files = os.listdir(constants.JSON_FILE_DIR)

list_series_dict=[]
for ff in list_files:
        if "json" in ff:
            match_number  = ff.split(".")[0]
            data = FlexDataRead().read_json(os.path.join(constants.JSON_FILE_DIR,ff))
            series_dict = {"series_name":"","series_date":"","season":"","match_id":""}
            for each in (data["info"]["dates"]):
                            #print(data["info"]["event"])
                            series_dict["series_date"]=each
                            try:
                                series_dict["series_name"] = data["info"]["event"]["name"]
                            except:
                                #print(data["info"])
                                series_dict["series_name"] =  data["info"]["teams"][0]+" tour of "+ data["info"]["teams"][1]
                            series_dict["season"] = data["info"]["season"]
                            series_dict["match_id"] = match_number
                            list_series_dict.append(series_dict)
df = pd.DataFrame(list_series_dict)
#df.drop_duplicates(inplace=True)

df_dates = df.groupby(["series_name","season"])["series_date"].aggregate(['min','max']).reset_index()
df_matches = df.groupby(['series_name','season'])['match_id'].agg(match_id_set_text= lambda x: set(x))
df_final = df_matches.merge(df_dates,how='inner',left_on=['series_name','season'],right_on=['series_name',"season"])
#df.columns =["series_name","season","series_start_date","series_end_date"]
#pd.DataFrame.from_dict(series_dict,orient='index').transpose()
df_final["match_id_set_text"]=df_final["match_id_set_text"].apply(lambda x:list(x))
df_final["match_id_set_text"]=df_final["match_id_set_text"].apply(json.dumps)
df_final["winner_id"]=None
#df = df.drop_duplicates()
print(df_final)

                         series_name   season  \
0          Afghanistan tour of India     2018
1                           Asia Cup     2008
2                           Asia Cup     2010
3                           Asia Cup     2004
4                           Asia Cup  2011/12
..                               ...      ...
213  West Indies v India T20I Series     2022
214                        World Cup     2019
215                        World T20  2013/14
216                        World T20  2015/16
217       Zimbabwe Triangular Series     2010

                                     match_id_set_text         min  \
0                                            [1133983]  2018-06-15
1     [335352, 335356, 335355, 335351, 335358, 335349]  2008-06-25
2                     [455234, 455236, 455237, 455232]  2010-06-16
3                                       [65718, 65716]  2004-07-27
4                             [535798, 535795, 535797]  2012-03-13
..                                                 ...         ...
213                                 [1317907, 1317906]  2022-08-06
214  [1144528, 1144520, 1144504, 1144490, 1144496, ...  2019-06-05
215   [682951, 682943, 682921, 682965, 682963, 682929]  2014-03-21
216           [951371, 951353, 951329, 951341, 951363]  2016-03-15
217                   [452147, 452146, 452149, 452150]  2010-05-28

            max winner_id
0    2018-06-15      None
1    2008-07-06      None
2    2010-06-24      None
3    2004-08-01      None
4    2012-03-18      None
..          ...       ...
213  2022-08-07      None
214  2019-07-10      None
215  2014-04-06      None
216  2016-03-31      None
217  2010-06-05      None

[218 rows x 6 columns]

In [ ]:
df.groupby(['series_name','season'])['match_id'].agg(match_id_set_text= lambda x: json.dumps(x))

series_name          object
season               object
match_id_set_text    object
min                  object
max                  object
winner_id            object
dtype: object

In [25]:
df

df_ = df.groupby(['series_name','season'])['match_id'].agg(set= lambda x: set(x))

In [37]:
#df["series_date"] = pd.to_datetime(df["series_date"])
#df["series_start_date"]=df.groupby(["series_name","season"]).agg({"series_date":"min"}).reset_index()["series_date"].tolist()[0]
#df["series_end_date"]=df.groupby(["series_name","season"]).agg({"series_date":"max"}).reset_index()["series_date"].tolist()[0]

                         series_name   season  \
0          Afghanistan tour of India     2018
1                           Asia Cup     2008
2                           Asia Cup     2010
3                           Asia Cup     2004
4                           Asia Cup  2011/12
..                               ...      ...
213  West Indies v India T20I Series     2022
214                        World Cup     2019
215                        World T20  2013/14
216                        World T20  2015/16
217       Zimbabwe Triangular Series     2010

                                     match_id_set_text         min  \
0                                            {1133983}  2018-06-15
1     {335352, 335356, 335355, 335351, 335358, 335349}  2008-06-25
2                     {455234, 455236, 455237, 455232}  2010-06-16
3                                       {65718, 65716}  2004-07-27
4                             {535798, 535795, 535797}  2012-03-13
..                                                 ...         ...
213                                 {1317907, 1317906}  2022-08-06
214  {1144528, 1144520, 1144504, 1144490, 1144496, ...  2019-06-05
215   {682951, 682943, 682921, 682965, 682963, 682929}  2014-03-21
216           {951371, 951353, 951329, 951341, 951363}  2016-03-15
217                   {452147, 452146, 452149, 452150}  2010-05-28

            max winner_id
0    2018-06-15      None
1    2008-07-06      None
2    2010-06-24      None
3    2004-08-01      None
4    2012-03-18      None
..          ...       ...
213  2022-08-07      None
214  2019-07-10      None
215  2014-04-06      None
216  2016-03-31      None
217  2010-06-05      None

[218 rows x 6 columns]

In [51]:
df_final["match_id_set_text"]=df_final["match_id_set_text"].apply(json.dumps)

In [53]:
df_final["match_id_set_text"].dtype

dtype('O')

In [11]:
df

,series_name,season,series_start_date,series_end_date,winner_id
0,Afghanistan tour of India,2018,2018-06-15,2018-06-15,None
1,Asia Cup,2008,2008-06-25,2008-07-06,None
2,Asia Cup,2010,2010-06-16,2010-06-24,None
3,Asia Cup,2004,2004-07-27,2004-08-01,None
4,Asia Cup,2011/12,2012-03-13,2012-03-18,None
...,...,...,...,...,...
213,West Indies v India T20I Series,2022,2022-08-06,2022-08-07,None
214,World Cup,2019,2019-06-05,2019-07-10,None
215,World T20,2013/14,2014-03-21,2014-04-06,None
216,World T20,2015/16,2016-03-15,2016-03-31,None
217,Zimbabwe Triangular Series,2010,2010-05-28,2010-06-05,None

In [87]:
from data_access_layer.read_sports_analysis_tables_from_postgres import ReadSportsAnalysisTablesPostgre
dss=ReadSportsAnalysisTablesPostgre()
df_series = dss.read_series_table()
#team_name_id =dict(zip(df_teams["team_name"],df_teams.team_id))

In [60]:

area_dict = dict(zip(df_series["series_id"], df_series["match_id_set_text"]))

In [64]:
pd.concat({k: pd.Series(v) for k, v in area_dict.items()})

1    0                                            [1133983]
2    0     [335349, 335351, 335352, 335355, 335356, 335358]
3    0                     [455232, 455234, 455236, 455237]
4    0                                       [65716, 65718]
5    0                             [535795, 535797, 535798]
                                ...
214  0                                   [1317906, 1317907]
215  0    [1144516, 1144520, 1144490, 1144522, 1144526, ...
216  0     [682951, 682921, 682929, 682963, 682965, 682943]
217  0             [951329, 951363, 951371, 951341, 951353]
218  0                     [452146, 452147, 452149, 452150]
Length: 218, dtype: object

In [82]:
df=pd.DataFrame.from_dict(area_dict,orient='columns')

ValueError: If using all scalar values, you must pass an index

In [86]:
df_series.explode("match_id_set_text")

,series_id,series_name,season,match_id_set_text,series_start_date,series_end_date,winner_id
0,1,Afghanistan tour of India,2018,[,2018-06-15,2018-06-15,None
0,1,Afghanistan tour of India,2018,1,2018-06-15,2018-06-15,None
0,1,Afghanistan tour of India,2018,1,2018-06-15,2018-06-15,None
0,1,Afghanistan tour of India,2018,3,2018-06-15,2018-06-15,None
0,1,Afghanistan tour of India,2018,3,2018-06-15,2018-06-15,None
...,...,...,...,...,...,...,...
217,218,Zimbabwe Triangular Series,2010,2,2010-05-28,2010-06-05,None
217,218,Zimbabwe Triangular Series,2010,1,2010-05-28,2010-06-05,None
217,218,Zimbabwe Triangular Series,2010,5,2010-05-28,2010-06-05,None
217,218,Zimbabwe Triangular Series,2010,0,2010-05-28,2010-06-05,None
217,218,Zimbabwe Triangular Series,2010,],2010-05-28,2010-06-05,None

In [85]:
df_series["match_id_set_text"]=df_series["match_id_set_text"].apply(lambda x :list(x))

ValueError: If using all scalar values, you must pass an index

In [89]:
df_series.dtypes

series_id                     int64
series_name                  object
season                       object
match_id_set_text            object
series_start_date    datetime64[ns]
series_end_date      datetime64[ns]
winner_id                    object
dtype: object

In [91]:
df_series.melt(id_vars = ['series_id'], value_name = "match_id_set_text")

/var/folders/17/gws30jys63j9xx5l0mwr5r4r0000gq/T/ipykernel_78155/4034890684.py:1: FutureWarning: This dataframe has a column name that matches the 'value_name' column name of the resulting Dataframe. In the future this will raise an error, please set the 'value_name' parameter of DataFrame.melt to a unique name.
  df_series.melt(id_vars = ['series_id'], value_name = "match_id_set_text")

      series_id     variable          match_id_set_text
0             1  series_name  Afghanistan tour of India
1             2  series_name                   Asia Cup
2             3  series_name                   Asia Cup
3             4  series_name                   Asia Cup
4             5  series_name                   Asia Cup
...         ...          ...                        ...
1303        214    winner_id                       None
1304        215    winner_id                       None
1305        216    winner_id                       None
1306        217    winner_id                       None
1307        218    winner_id                       None

[1308 rows x 3 columns]

In [94]:
df_series.explode("match_id_set_text")
from ast import literal_eval

df_series['match_id_set_text'] = df_series['match_id_set_text'].apply(literal_eval)
df_series.explode("match_id_set_text")

,series_id,series_name,season,match_id_set_text,series_start_date,series_end_date,winner_id
0,1,Afghanistan tour of India,2018,1133983,2018-06-15,2018-06-15,None
1,2,Asia Cup,2008,335349,2008-06-25,2008-07-06,None
1,2,Asia Cup,2008,335351,2008-06-25,2008-07-06,None
1,2,Asia Cup,2008,335352,2008-06-25,2008-07-06,None
1,2,Asia Cup,2008,335355,2008-06-25,2008-07-06,None
...,...,...,...,...,...,...,...
216,217,World T20,2015/16,951353,2016-03-15,2016-03-31,None
217,218,Zimbabwe Triangular Series,2010,452146,2010-05-28,2010-06-05,None
217,218,Zimbabwe Triangular Series,2010,452147,2010-05-28,2010-06-05,None
217,218,Zimbabwe Triangular Series,2010,452149,2010-05-28,2010-06-05,None
217,218,Zimbabwe Triangular Series,2010,452150,2010-05-28,2010-06-05,None

In [97]:
df_series.dtypes

series_id                     int64
series_name                  object
season                       object
match_id_set_text            object
series_start_date    datetime64[ns]
series_end_date      datetime64[ns]
winner_id                    object
dtype: object

In [129]:
list(set(data["info"]["teams"]).symmetric_difference( (data["innings"][0]["team"]).split()) )[0]

'India'

In [127]:
data["innings"][0]["team"].split()

['Australia']

In [107]:
construct_match_id_innings_number_dict={}
for k,v in df_s.iterrows():
    construct_match_id_innings_number_dict[v["inning_id"]]=(v["match_id"],v["innings_number"])

In [111]:
for x,(y,z) in construct_match_id_innings_number_dict.items():
    print(z)

0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
3
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
2
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
2
3
0
1
2
3
0
1
2
3
0
1
2
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
0
1
2
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
2
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
0
1
0
1
0
1
0
1
0
1
0
1
0
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
0
1
0
1
2
3
0
1
2
3
0
1
0
1
2
0
1
2
3
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
2
3
0
1
0
1
2
3
0
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
2
3
0
1
2
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
2
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
2
0
1
0
1
2
3
0
1
2
0
1
0
1
0
1
0
1
2
0
1
2
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
3
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
2
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
0
0
1
2
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
3
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
2
3
0
1
2
0
1
0
1
0
1
0
1
0
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
2
0
1
2
0
1
0
1
0
1
2
3
0
1
2
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
3
0
1
2
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
0
1
0
1
0
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
0
1
2
0
1
0
1
0
1
0
1
0
0
1
2
3
0
1
0
1
0
1
0
1
2
3
0
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
0
1
2
3
0
1
2
0
1
0
1
2
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
1
0
1
2
3
0
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
2
0
1
0
1
0
1
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
1
0
1
0
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
2
3
0
1
0
1
0
1
0
1
2
0
1
0
1
2
3
0
1
0
1
2
3
0
1
2
0
1
2
3
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
2
3
0
1
0
1
2
3
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
2
3
0
1
2
3
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
2
3
0
0
1
0
1
2
3
0
1
0
1
0
1
2
3
0
1
0
1
2
0
1
2
3
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
2
3
0
1
0
1
2
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
0
1
2
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
2
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
2
3
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
2
0
1
0
1
0
1
2
0
1

In [132]:
"west Indies".split("-")

['west Indies']

In [134]:
df_matches_innings_table = dss.read_matches_innings_table()

In [140]:
stress = df_matches_innings_table.groupby("match_id")["inning_id"].apply(list).to_dict()
stress

{64047: [184, 185, 186],
 64059: [1145, 1146, 1147, 1148],
 64062: [1299, 1300, 1301, 1302],
 64083: [965, 966, 967],
 64100: [1706, 1707, 1708, 1709],
 64102: [197, 198, 199, 200],
 64109: [790, 791, 792],
 64110: [1024, 1025, 1026, 1027],
 64111: [1532, 1533, 1534],
 64814: [1885, 1886],
 64815: [1674, 1675],
 64816: [248, 249],
 64817: [224, 225],
 64819: [1555, 1556],
 64882: [356, 357],
 64883: [121, 122],
 64884: [1010, 1011],
 64885: [487, 488],
 64914: [915, 916],
 64917: [1057, 1058],
 64939: [537, 538],
 64941: [1492, 1493],
 64942: [541, 542],
 64943: [927, 928],
 65032: [1968, 1969],
 65033: [1593, 1594],
 65034: [1344, 1345],
 65241: [564, 565],
 65244: [1867, 1868],
 65250: [287, 288],
 65257: [550, 551],
 65262: [1275, 1276],
 65268: [1762, 1763],
 65276: [814, 815],
 65278: [1459, 1460],
 65281: [1411, 1412],
 65285: [351, 352],
 65286: [1752, 1753],
 65643: [1891, 1892],
 65645: [1541, 1542],
 65647: [883, 884],
 65648: [1151, 1152],
 65649: [1399, 1400],
 65653: [1490, 1491],
 65655: [1825, 1826],
 65656: [187, 188],
 65716: [1478, 1479],
 65718: [786, 787],
 66198: [1383, 1384],
 66207: [878, 879],
 66356: [1498],
 66364: [466],
 66365: [23, 24],
 66367: [1641, 1642],
 66369: [133, 134],
 66372: [454, 455],
 66374: [834, 835],
 66375: [645],
 214742: [923, 924],
 217481: [1035, 1036],
 217979: [293, 294],
 218250: [1933, 1934],
 219062: [918, 919, 920],
 223018: [1461, 1462],
 223334: [180, 181],
 223902: [620, 621],
 224231: [1401, 1402],
 224556: [438, 439],
 225437: [1077, 1078],
 225959: [1869, 1870],
 226359: [1815, 1816],
 226363: [1861, 1862, 1863, 1864],
 233797: [608, 609, 610, 611],
 234783: [45, 46, 47, 48],
 235831: [1758, 1759],
 236520: [981, 982],
 236809: [574, 575],
 237222: [495, 496],
 237571: [218, 219],
 238186: [147, 148, 149, 150],
 238188: [1633, 1634],
 238189: [1907, 1908],
 238190: [169, 170],
 238193: [1803, 1804],
 238194: [1096, 1097],
 239025: [1141, 1142, 1143, 1144],
 239916: [1736, 1737],
 239917: [1797, 1798],
 239918: [49, 50],
 239919: [452, 453],
 239920: [1557, 1558, 1559, 1560],
 239921: [2015, 2016, 2017],
 239922: [105, 106, 107, 108],
 239923: [362, 363, 364, 365],
 244510: [358, 359],
 244511: [103, 104],
 247464: [139, 140],
 247468: [17, 18],
 247476: [1098, 1099],
 249211: [117, 118],
 249212: [1769, 1770],
 249213: [1760, 1761],
 249214: [1409, 1410],
 249215: [1133, 1134, 1135, 1136],
 249216: [1006, 1007, 1008, 1009],
 249217: [483, 484, 485, 486],
 249745: [159, 160],
 249753: [131, 132],
 249756: [1424, 1425],
 255954: [1271, 1272],
 256607: [1563, 1564],
 256608: [234, 235],
 256612: [420, 421],
 256614: [804, 805],
 256665: [303],
 258468: [1482, 1483, 1484, 1485],
 258469: [1065, 1066, 1067, 1068],
 258470: [728, 729, 730, 731],
 258471: [724, 725],
 258472: [1397, 1398],
 258473: [1139, 1140],
 258474: [2011, 2012],
 258475: [1553, 1554],
 258476: [368, 369],
 258477: [111, 112],
 267708: [430, 431],
 267709: [64, 65],
 267710: [1768],
 267712: [349, 350],
 267713: [115, 116],
 267715: [481, 482],
 275789: [1303, 1304],
 282688: [685, 686],
 282689: [793, 794],
 282691: [1535, 1536, 1537, 1538],
 282692: [582, 583, 584],
 287862: [366, 367],
 287865: [726, 727],
 287873: [683, 684],
 287876: [1956, 1957],
 287878: [297, 298],
 287879: [191, 192],
 291351: [1791, 1792, 1793, 1794],
 291352: [135, 136, 137, 138],
 291353: [328, 329, 330, 331],
 291354: [511, 512, 513],
 291356: [1106, 1107],
 291359: [852, 853],
 291360: [1202],
 291362: [679, 680],
 291365: [424, 425],
 291366: [1595, 1596],
 291368: [201, 202],
 291369: [295, 296],
 291371: [2000, 2001],
 291372: [93, 94],
 293071: [416, 417],
 293076: [681, 682],
 293077: [780, 781],
 293078: [1069, 1070],
 297793: [145, 146],
 297794: [983, 984],
 297795: [514, 515],
 297796: [1436, 1437],
 297797: [1104, 1105],
 297798: [860, 861],
 297799: [630, 631],
 297800: [1728, 1729],
 297801: [1811, 1812],
 297802: [174, 175],
 297803: [306, 307],
 297804: [522, 523],
 297805: [945, 946],
 297806: [1087, 1088, 1089, 1090],
 297807: [1467, 1468, 1469, 1470],
 297808: [668, 669, 670, 671],
 332911: [1028, 1029, 1030],
 332912: [889, 890, 891],
 332913: [587, 588, 589, 590],
 335349: [1283, 1284],
 335351: [972, 973],
 335352: [1102, 1103],
 335355: [1795, 1796],
 335356: [155, 156],
 335358: [1613, 1614],
 343729: [274, 275, 276],
 343730: [1577, 1578, 1579, 1580],
 343731: [1986, 1987, 1988, 1989],
 343732: [78, 79],
 343733: [400, 401],
 343734: [702, 703],
 343736: [1176, 1177],
 345469: [212, 213],
 345470: [1980, 1981],
 345471: [1587, 1588],
 345669: [320, 321, 322, 323],
 345670: [1635, 1636, 1637, 1638],
 345671: [1911, 1912, 1913, 1914],
 345672: [27, 28, 29, 30],
 355994: [195, 196],
 356001: [1123, 1124],
 356006: [1773, 1774],
 356010: [1819, 1820],
 356014: [943, 944],
 361043: [658, 659],
 361044: [436, 437],
 361045: [68, 69],
 361046: [1940, 1941],
 361047: [1597, 1598],
 361050: [1903, 1904, 1905, 1906],
 361051: [1655, 1656, 1657, 1658],
 366341: [1338, 1339],
 366622: [1085, 1086],
 366623: [1463, 1464],
 366624: [1730, 1731],
 366625: [1813, 1814],
 366626: [171],
 366627: [304, 305],
 366628: [1599, 1600, 1601, 1602],
 366629: [1942, 1943, 1944, 1945],
 377313: [442, 443],
 377314: [652, 653],
 377315: [816, 817],
 377316: [1217],
 386494: [1315, 1316],
 386496: [811, 812, 813],
 386530: [955, 956],
 386531: [535, 536],
 386532: [1457, 1458],
 386533: [1079, 1080],
 386534: [1805, 1806],
 386535: [1720, 1721],
 403381: [1263, 1264],
 403382: [612, 613],
 403383: [870, 871],
 412679: [704, 705],
 412682: [1184, 1185],
 412691: [384, 385],
 412695: [1371, 1372],
 412699: [1520, 1521],
 415278: [1178, 1179],
 415281: [1190],
 415284: [412, 413],
 416236: [240, 241],
 416237: [220, 221],
 416238: [2018, 2019],
 416239: [1561, 1562],
 416240: [15, 16],
 416241: [471, 472],
 430881: [1017, 1018, 1019],
 430882: [880, 881, 882],
 430883: [597, 598, 599],
 430884: [238, 239],
 430885: [230, 231],
 430886: [1893, 1894],
 430887: [1668, 1669],
 430888: [376, 377],
 430889: [95, 96],
 430890: [1833],
 433558: [618, 619],
 433568: [207, 208],
 433578: [566, 567],
 433582: [1505, 1506],
 433586: [291, 292],
 433599: [1163, 1164],
 433601: [236, 237],
 433605: [1545, 1546],
 433606: [595, 596],
 434256: [1683, 1684, 1685, 1686],
 434257: [1853, 1854, 1855, 1856],
 434259: [382, 383],
 434260: [1607, 1608],
 434262: [60, 61],
 434263: [432, 433],
 434264: [660, 661],
 441825: [1191, 1192, 1193],
 441826: [773, 774, 775],
 441827: [691, 692],
 441828: [1511, 1512],
 441829: [1049, 1050],
 452146: [1801, 1802],
 452147: [1738, 1739],
 452149: [43, 44],
 452150: [1781, 1782],
 452153: [129, 130],
 452154: [985, 986],
 455232: [448, 449],
 455234: [824, 825],
 455236: [1297, 1298],
 455237: [1220, 1221],
 456662: [858, 859],
 456663: [628, 629],
 456665: [25, 26],
 456666: [1909, 1910],
 456668: [335, 336],
 456669: [141, 142, 143, 144],
 456670: [1928, 1929, 1930],
 456671: [1619, 1620, 1621, 1622],
 463146: [799, 800, 801],
 463147: [675, 676, 677, 678],
 463148: [1501, 1502, 1503, 1504],
 463149: [1063, 1064],
 463150: [734, 735],
 463151: [714, 715],
 463152: [1387, 1388],
 463153: [1156, 1157],
 463154: [2006, 2007],
 464526: [1403, 1404, 1405, 1406],
 464527: [1129, 1130, 1131, 1132],
 464529: [616, 617],
 464531: [1081, 1082, 1083, 1084],
 464532: [957, 958, 959, 960],
 464533: [532, 533, 534],
 467883: [5, 6],
 467884: [864, 865],
 467885: [604, 605],
 467886: [1269, 1270],
 467887: [1253, 1254],
 474472: [1724, 1725, 1726, 1727],
 474473: [1807, 1808, 1809, 1810],
 474474: [1091, 1092, 1093],
 474475: [1471, 1472, 1473],
 474476: [524, 525],
 474477: [947, 948],
 474478: [1209, 1210],
 474479: [1319, 1320],
 474480: [1273, 1274],
 474481: [1241, 1242],
 489220: [456, 457],
 489221: [37, 38],
 489222: [1931, 1932],
 489223: [1625, 1626],
 489224: [1295, 1296],
 489225: [1227, 1228],
 489226: [830, 831, 832, 833],
 489227: [641, 642, 643, 644],
 489228: [1452, 1453, 1454, 1455],
 518950: [708, 709, 710, 711],
 518951: [746, 747, 748],
 518952: [1165, 1166, 1167],
 518953: [1375, 1376, 1377, 1378],
 518954: [1573, 1574],
 518955: [1992, 1993],
 518956: [85, 86],
 518957: [392, 393],
 518959: [1857, 1858],
 518960: [172, 173],
 518962: [1732, 1733],
 518963: [1817, 1818],
 518965: [1465, 1466],
 518966: [530, 531],
 521217: [820, 821],
 521218: [1100, 1101],
 521219: [1446, 1447],
 521220: [580, 581],
 521221: [885, 886],
 521222: [1033, 1034],
 533274: [1722, 1723],
 533281: [1647, 1648],
 533287: [1245, 1246],
 533291: [1211, 1212],
 533295: [66, 67],
 535795: [722, 723],
 535797: [1149, 1150],
 535798: [887, 888],
 535997: [1265, 1266, 1267, 1268],
 535998: [492, 493, 494],
 535999: [996, 997, 998, 999],
 536929: [1305, 1306],
 536930: [505, 506],
 536931: [990, 991],
 536932: [1114, 1115],
 536933: [1428, 1429],
 556252: [109, 110],
 564781: [925, 926],
 564782: [1071, 1072],
 564783: [1494, 1495],
 564784: [1712, 1713],
 564785: [1827, 1828],
 564786: [189, 190],
 565806: [526, 527, 528, 529],
 565807: [951, 952, 953, 954],
 565808: [1213, 1214, 1215, 1216],
 565809: [1321, 1322, 1323],
 565810: [479, 480],
 565811: [1004, 1005],
 565812: [1137, 1138],
 565813: [1413, 1414],
 565814: [1754, 1755],
 565815: [1764, 1765],
 565816: [119, 120],
 565817: [353, 354, 355],
 565818: [1651, 1652, 1653, 1654],
 565820: [76, 77],
 566947: [1119, 1120],
 566948: [868, 869],
 578614: [360, 361],
 578619: [222, 223],
 578623: [157, 158],
 589306: [1336, 1337],
 589307: [1200, 1201],
 589308: [939, 940],
 589309: [545, 546],
 589310: [1395, 1396],
 597924: [1393, 1394],
 597925: [1161, 1162],
 597926: [732, 733],
 597928: [1547, 1548],
 597929: [1020, 1021],
 598812: [1186, 1187, 1188, 1189],
 598813: [1361, 1362, 1363],
 598814: [1581, 1582, 1583, 1584],
 598815: [1972, 1973, 1974, 1975],
 643665: [900, 901],
 643667: [1526, 1527],
 643669: [756, 757],
 643675: [279, 280],
 643677: [1840, 1841],
 647247: [51, 52],
 647249: [1714, 1715],
 647251: [7, 8],
 647253: [1661, 1662],
 647255: [1255, 1256],
 647259: [1125, 1126],
 647261: [562, 563],
 648651: [1710, 1711],
 648653: [193, 194],
 648655: [547],
 648665: [33, 34, 35, 36],
 648667: [1629, 1630, 1631, 1632],
 656405: [1229, 1230],
 656423: [1704, 1705],
 656439: [1565, 1566],
 656453: [1311, 1312],
 656465: [1528, 1529],
 656475: [1842, 1843],
 656485: [697, 698],
 656493: [689, 690],
 667641: [1094, 1095],
 667643: [520, 521],
 667645: [167, 168],
 667647: [1734, 1735],
 667649: [41, 42],
 667651: [1740, 1741, 1742, 1743],
 667653: [151, 152, 153, 154],
 667711: [978, 979, 980],
 667713: [1438, 1439, 1440, 1441],
 667715: [1787, 1788, 1789, 1790],
 667717: [332, 333, 334],
 667719: [1917, 1918, 1919],
 667723: [1950, 1951],
 667725: [1326, 1327],
 667727: [802, 803],
 667729: [1496, 1497],
 667731: [740, 741],
 676525: [1366, 1367, 1368],
 676527: [758, 759, 760],
 676529: [1524, 1525],
 676531: [776, 777],
 676533: [1342, 1343],
 682921: [450, 451],
 682929: [1450, 1451],
 682943: [1689, 1690],
 682951: [552, 553],
 682963: [1643, 1644],
 682965: [1243, 1244],
 710293: [434, 435],
 710297: [1317, 1318],
 710301: [1996, 1997],
 710307: [1373, 1374],
 744679: [1883, 1884],
 744681: [1693, 1694],
 744683: [211],
 754737: [1172, 1173, 1174, 1175],
 754739: [576, 577, 578, 579],
 754741: [1442, 1443, 1444, 1445],
 754743: [974, 975, 976, 977],
 754749: [460, 461],
 754753: [312, 313],
 754757: [1456],
 754759: [828, 829],
 770121: [1448, 1449],
 770123: [970, 971],
 770127: [1799, 1800],
 792289: [1871, 1872],
 792291: [404, 405],
 792293: [1982, 1983],
 792295: [1364, 1365],
 792297: [763, 764],
 870729: [1958, 1959, 1960],
 870731: [242, 243],
 870733: [1889, 1890],
 870735: [1543, 1544],
 885959: [1053, 1054],
 885965: [1748, 1749],
 885967: [127, 128],
 885969: [1663, 1664],
 885971: [178, 179],
 895773: [1829, 1830, 1831, 1832],
 895775: [1486, 1487, 1488, 1489],
 895777: [935, 936, 937, 938],
 895807: [1369, 1370],
 895809: [896, 897],
 895811: [1346, 1347],
 895813: [771, 772],
 895815: [408, 409],
 895817: [1970, 1971],
 895819: [268, 269],
 895821: [1771, 1772],
 903587: [1507, 1508],
 903589: [765, 766],
 903593: [904, 905],
 903595: [260, 261],
 903597: [1865, 1866],
 903599: [390, 391],
 903601: [1012, 1013],
 903603: [600, 601, 602, 603],
 903605: [228, 229],
 903607: [1670, 1671, 1672, 1673],
 903609: [99, 100, 101, 102],
 951329: [639, 640],
 951341: [1984, 1985],
 951353: [742, 743],
 951363: [310, 311],
 951371: [1407, 1408],
 963697: [262, 263],
 963699: [1994, 1995],
 963701: [949, 950],
 966745: [277, 278],
 966751: [1881, 1882],
 966757: [1522, 1523],
 966761: [1313, 1314],
 966765: [440, 441],
 1007649: [1744, 1745],
 1007651: [55, 56],
 1007653: [1609, 1610],
 1007655: [1218, 1219],
 1007657: [656, 657],
 1007659: [1073, 1074],
 1022353: [929, 930],
 1022361: [1920, 1921],
 1022367: [1285, 1286],
 1022373: [822, 823],
 1022375: [446, 447],
 1022593: [1665, 1666, 1667],
 1022595: [1014, 1015, 1016],
 1022597: [591, 592, 593, 594],
 1022599: [1153],
 1030213: [1430, 1431, 1432, 1433],
 1030215: [1783, 1784, 1785, 1786],
 1030217: [337, 338, 339, 340],
 1030219: [1922, 1923],
 1030221: [418, 419],
 1030223: [1954, 1955],
 1030225: [1334, 1335],
 1030227: [788, 789],
 1034809: [396, 397, 398, 399],
 1034811: [1844, 1845, 1846, 1847],
 1034813: [270, 271, 272, 273],
 1034815: [908, 909, 910],
 1034817: [1515, 1516, 1517],
 1034819: [769, 770],
 1034821: [1257, 1258],
 1034823: [874, 875],
 1034825: [473, 474],
 1034827: [1899, 1900],
 1034829: [347, 348],
 1041615: [1750, 1751],
 1041617: [125, 126],
 1041761: [1357, 1358, 1359, 1360],
 1062573: [1777, 1778, 1779, 1780],
 1062574: [1108, 1109, 1110, 1111],
 1062575: [1421, 1422, 1423],
 1062576: [507, 508, 509, 510],
 1098206: [917],
 1098207: [556, 557],
 1098208: [1354, 1355],
 1098209: [1182, 1183],
 1098210: [906, 907],
 1098211: [568, 569],
 1109602: [664, 665, 666, 667],
 1109603: [808, 809, 810],
 1109604: [57, 58, 59],
 1109605: [426, 427],
 1109606: [1603, 1604],
 1109607: [1946, 1947],
 1109608: [176, 177],
 1109609: [308, 309],
 1109610: [1649, 1650],
 1119496: [876, 877],
 1119497: [614, 615],
 1119498: [1417, 1418],
 1119499: [1121, 1122],
 1119500: [406, 407],
 1119501: [70, 71],
 1119502: [1966, 1967],
 1119543: [2004, 2005],
 1119544: [1154, 1155],
 1119545: [1385, 1386],
 1119546: [716, 717],
 1119547: [736, 737],
 1119548: [1022, 1023],
 1119549: [1549, 1550, 1551, 1552],
 1119550: [672, 673, 674],
 1119551: [795, 796, 797, 798],
 1119552: [1203, 1204, 1205, 1206],
 1119553: [1328, 1329, 1330, 1331],
 1120090: [1948, 1949],
 1120091: [1605, 1606],
 1120092: [428, 429],
 1120093: [62, 63],
 1120094: [806, 807],
 1120095: [662, 663],
 1122276: [163, 164, 165, 166],
 1122277: [316, 317, 318, 319],
 1122278: [1615, 1616, 1617, 1618],
 1122279: [1924, 1925],
 1122280: [1915, 1916],
 1122281: [1639, 1640],
 1122282: [464, 465],
 1122283: [21, 22],
 1122284: [850, 851],
 1122285: [626, 627],
 1122286: [1281, 1282],
 1122287: [1239, 1240],
 1122723: [341, 342, 343, 344],
 1122724: [489, 490, 491],
 1122725: [992, 993, 994, 995],
 1122726: [1127, 1128],
 1122727: [1419, 1420],
 1122728: [606, 607],
 1122729: [866, 867],
 1122730: [1075, 1076],
 1122731: [1474, 1475],
 1133817: [761, 762],
 1133818: [1041, 1042],
 1133820: [539, 540],
 1133821: [941, 942],
 1133823: [1476, 1477],
 1133983: [1937, 1938, 1939],
 1140992: [1350, 1351],
 1140993: [1196, 1197],
 1144490: [394, 395],
 1144496: [754, 755],
 1144504: [1307, 1308],
 1144510: [872, 873],
 1144516: [475, 476],
 1144520: [266, 267],
 1144522: [1848, 1849],
 1144526: [911, 912],
 1144528: [1352, 1353],
 1144990: [1389, 1390],
 1144991: [1158],
 1144992: [738, 739],
 1144993: [718, 719, 720, 721],
 1144994: [370, 371, 372, 373],
 1144995: [87, 88, 89, 90],
 1144996: [2008, 2009, 2010],
 1144997: [1569, 1570],
 1144998: [232, 233],
 1144999: [226, 227],
 1153246: [97, 98],
 1153247: [378, 379],
 1153249: [1895, 1896],
 1153251: [422, 423],
 1153253: [1952, 1953],
 1153255: [1324, 1325],
 1153691: [1309, 1310],
 1153692: [654, 655],
 1153693: [818, 819],
 1153694: [53, 54],
 1153695: [444, 445],
 1153696: [1611, 1612],
 1153697: [1935, 1936],
 1153698: [182, 183],
 1157752: [1963, 1964, 1965],
 1157753: [1589, 1590, 1591, 1592],
 1157754: [1348, 1349],
 1157755: [1194, 1195],
 1157756: [767, 768],
 1157757: [687, 688],
 1157758: [1513, 1514],
 1157759: [1055, 1056],
 1157760: [1002, 1003],
 1157761: [501, 502],
 1168242: [622, 623],
 1168243: [862, 863],
 1168244: [13, 14],
 1168245: [469, 470],
 1168246: [1645, 1646],
 1168247: [1901, 1902],
 1168248: [123, 124],
 1187005: [572, 573],
 1187006: [1530, 1531],
 1187007: [1045, 1046, 1047, 1048],
 1187008: [751, 752, 753],
 1187009: [699, 700, 701],
 1187013: [558, 559],
 1187014: [264, 265],
 1187015: [209, 210],
 1187016: [1850, 1851, 1852],
 1187017: [1695, 1696, 1697],
 1187018: [410, 411],
 1187019: [72, 73],
 1187020: [1897, 1898],
 1187021: [1659, 1660],
 1187022: [477, 478],
 1187023: [9, 10],
 1187027: [1251, 1252],
 1187028: [1000, 1001],
 1187029: [497, 498],
 1187677: [1340, 1341],
 1187678: [543, 544],
 1187679: [931, 932, 933, 934],
 1187680: [892, 893, 894, 895],
 1187681: [585, 586],
 1187682: [1539, 1540],
 1187683: [1031, 1032],
 1187684: [1887, 1888],
 1187685: [1676, 1677, 1678, 1679],
 1187686: [244, 245, 246, 247],
 1188621: [345, 346],
 1188622: [1746, 1747],
 1188623: [1775, 1776],
 1188624: [1118],
 1188625: [1415, 1416],
 1188626: [499, 500],
 1188628: [1247, 1248, 1249, 1250],
 1188629: [1259, 1260, 1261, 1262],
 1202243: [1043, 1044],
 1202244: [1875, 1876],
 1223869: [1, 2, 3, 4],
 1223870: [1821, 1822, 1823, 1824],
 1223871: [1716, 1717, 1718, 1719],
 1223872: [299, 300, 301, 302],
 1223952: [1391, 1392],
 1223953: [1159, 1160],
 1223954: [2002, 2003],
 1223955: [1567, 1568],
 1223956: [374, 375],
 1223957: [91, 92],
 1239543: [1037, 1038, 1039, 1040],
 1239544: [1877, 1878, 1879, 1880],
 1239545: [1680, 1681, 1682],
 1239546: [252, 253, 254, 255],
 1243384: [836, 837, 838, 839],
 1243385: [646, 647, 648, 649],
 1243386: [1291, 1292, 1293, 1294],
 1243387: [1224, 1225, 1226],
 1243388: [961, 962],
 1243389: [516, 517],
 1243390: [1279, 1280],
 1243391: [1237, 1238],
 1243392: [848, 849],
 1243393: [624, 625],
 1243394: [462, 463],
 1243395: [19, 20],
 1249875: [782, 783, 784, 785],
 1262755: [113, 114],
 1262756: [1766, 1767],
 1262757: [1756, 1757],
 1262758: [467, 468],
 1262759: [11, 12],
 1262760: [1976, 1977],
 1273727: [1235, 1236],
 1273739: [161, 162],
 1273744: [560, 561],
 1273748: [693, 694],
 1273753: [898, 899],
 1276904: [1499, 1500],
 1276905: [1061, 1062],
 1276906: [921, 922],
 1276907: [548, 549],
 1276908: [1332, 1333],
 1276909: [1207, 1208],
 1277079: [283, 284, 285, 286],
 1277080: [256, 257, 258, 259],
 1277081: [214, 215, 216, 217],
 1277082: [1859, 1860],
 1277083: [1687, 1688],
 1277084: [1518, 1519],
 1278671: [554, 555],
 1278672: [1509, 1510],
 1278673: [1059, 1060],
 1278674: [1836, 1837, 1838, 1839],
 1278675: [1700, 1701, 1702, 1703],
 1278676: [281, 282],
 1278677: [203, 204],
 1278678: [1978, 1979],
 1278679: [1585, 1586],
 1278680: [1571, 1572],
 1278681: [1990, 1991],
 1278682: [82, 83, 84],
 1278683: [386, 387, 388, 389],
 1278684: [712, 713],
 1278685: [749, 750],
 1278686: [1168, 1169],
 1278687: [1379, 1380],
 1278688: [570, 571],
 1278689: [902, 903],
 1278690: [1180, 1181],
 1278691: [1356],
 1298150: [842, 843],
 1298157: [31, 32],
 1298164: [1480, 1481],
 1298169: [1198, 1199],
 1298176: [250, 251],
 1298178: [2013, 2014],
 1303307: [1627, 1628],
 1303308: [314, 315],
 1317900: [380, 381],
 1317901: [80, 81],
 1317902: [1998, 1999],
 1317903: [1575, 1576],
 1317904: [1381, 1382],
 1317905: [1170, 1171],
 1317906: [744, 745],
 1317907: [706, 707],
 1320741: [324, 325, 326, 327],
 1322276: [1231, 1232],
 1322277: [1287, 1288],
 1322278: [503, 504],
 1322279: [989],
 1322280: [968, 969],
 1325549: [826, 827],
 1325550: [1112, 1113],
 1325551: [1426, 1427],
 1327270: [414, 415],
 1327272: [1961, 1962],

In [143]:
stress[1223869]

[1, 2, 3, 4]

In [142]:
for x,y in enumerate([1,2,3,5,6,7]):
    print(x,y)

0 1
1 2
2 3
3 5
4 6
5 7